### ISSUE TITLE
Variable definitions in train.py 

### ISSUE THREAD

**Issue by Sidney2408** [abedicodes/ResNet-TCN#2]
Hi there, I tried running your code on the DAISEE dataset, and I cannot help but notice a few variables that are not defined:
In train.py
1.  Traceback (most recent call last):
  File "train.py", line 95, in <module>
    writeUnNormalize(inputs, phase)
  File "train.py", line 40, in writeUnNormalize
    cv2.imwrite(os.path.join(images, 'images_' + phase, 'image_' + str(i) + '.png'), image)
NameError: name 'images' is not defined

2.  Traceback (most recent call last):
  File "train.py", line 15, in <module>
    import transforms_train
ModuleNotFoundError: No module named 'transforms_train'

3.  Traceback (most recent call last):
  File "train.py", line 83, in <module>
    root),
NameError: name 'root' is not defined

4. Traceback (most recent call last):
  File "train.py", line 81, in <module>
    os.path.join(data_path, 'train.csv'),
NameError: name 'data_path' is not defined

**Comment by abediai** [comment]
Hi, Please run the modified version in which all the variables have been defined.

**Comment by abedicodes** [comment]
Defining variables
