### ISSUE TITLE
Time Steps in the code 

### ISSUE THREAD

**Issue by Sidney2408** [abedicodes/ResNet-TCN#5]
Hi Abedi, I would like to clarify the some implementation in transforms.py. In the paper, it was said that there were 50 timesteps extracted from the video, so I was wondering, are these time steps consecutive, (i.e. 1.jpg, 2.jpg, etc) or are they extracted throughout the video (i.e. 1.jpg, 3.jpg, ..., 100.jpg ).

**Comment by abediai** [comment]
The timestamps are extracted throughout the video, i.e. by downsampling the video.
