### ISSUE TITLE
model weights

### ISSUE THREAD

**Issue by chengyu0910** [abedicodes/ResNet-TCN#7]
Hi, thanks for your great work and sharing!  Will you share the trained model weights?

**Comment by abediai** [comment]
Thanks for your interest. Currently, I do not have the trained models saved for sharing. When I recreate them, I will inform you.

**Comment by chengyu0910** [comment]
> Thanks for your interest. Currently, I do not have the trained models saved for sharing. When I recreate them, I will inform Thanks!  I will try to reproduce it too.

**Comment by chengyu0910** [comment]
> Thanks for your interest. Currently, I do not have the trained models saved for sharing. When I recreate them, I will inform you.

Hi, I want to know whether the trained model parameters are recreated? My device is limit, so the reproducement is hard.
